name: StatsImporter
main: de.gilde.statsimporter.ImporterPlugin
version: ${version}
api-version: "26.1.2"
folia-supported: true
author: CFPlusPlus
description: Importiert Minecraft-Statistiken in eine MariaDB für Ranglisten-Metriken.
permissions:
  statsimporter.admin:
    default: op
